import type {Metadata} from "next";
import {Geist, Geist_Mono, Kanit, Roboto} from "next/font/google";
import "../globals.css";

const roboto = Roboto({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "900"],
});

const kanit = Kanit({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Vulnerable Voting System - Login",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${roboto.className} antialiased`}>
        <div
          className="w-full relative h-screen bg-cover bg-center flex justify-center items-center z-1"
          style={{backgroundImage: "url('login-bg.jpg')"}}
        >
          <div className="absolute inset-0 bg-white bg-opacity-50 h-screen" />
          {children}
        </div>
      </body>
    </html>
  );
}
