import type {Metadata} from "next";
import {Roboto} from "next/font/google";
import "../globals.css";
import {AuthProvider} from "@/context/authContext";

const roboto = Roboto({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Vulnerable Voting System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${roboto.className} antialiased`}>
        <AuthProvider>
          <div className="w-full flex justify-center px-10 py-10 bg-neutral-200">
            {children}
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
